"""Exact arithmetic for the reconstruction programme.

Four mechanisms, all deterministic and exact (integer and rational
arithmetic throughout; no floats except in reported densities):

1. The one-generation ledger. The 16 left-handed Weyl states of one
   Standard Model generation, their hypercharges as exact fractions, the
   five consistency sums (two mixed gauge anomalies, the cubic
   hypercharge anomaly, the mixed gravitational anomaly, and the Witten
   SU(2) doublet parity), and the deletion-rigidity table: which sums
   break when each multiplet is removed. The right-handed neutrino is the
   one multiplet whose deletion breaks nothing.

2. The global-form atlas. The center-class group Z3 x Z2 x Z6, the
   screening subgroup generated by the six matter classes, and, for each
   subgroup Gamma of Z6, the surviving electric line classes, the
   magnetic classes, the integrality of the Dirac pairing, and the
   admissibility of all six matter multiplets under all four global
   forms: identical perturbation theory, four distinct theories.

3. The SL(2,Z) orbit. Over a charge box, membership in the orbit of the
   unit electric charge coincides with coprimality, witnessed by explicit
   Bezout matrices of determinant 1; the coprime density approaches
   6/pi^2; and every primitive vector decomposes into two nonzero
   constituents, which is the no-go: primitive labels never establish
   indivisible carriers.

4. The fusion counterexamples. In SU(3), the singlet appears exactly once
   in 3 x 3 x 3 and never in 3 x 3 (the proton toy: simple and
   composite). In the SU(2) fusion ring, every irreducible is
   tensor-prime while every spin above one half is a summand of a product
   of smaller spins: the bound-state relation is a summand, never a
   factor, so tensor-primality detects nothing.

Invariants fail the run.
"""
from __future__ import annotations

import math
from fractions import Fraction as F
from itertools import product

SEED = 20260823   # unused randomness; everything here is exact

# ----------------------------------------------------------------------
# mechanism 1: the one-generation ledger
# ----------------------------------------------------------------------

# (name, dim SU(3), dim SU(2), hypercharge Y, Dynkin index T3, T2)
# All fields left-handed Weyl; T(fund) = 1/2 per factor, 0 for singlets.
GENERATION = [
    ("qL",    3, 2, F(1, 6)),
    ("dbarR", 3, 1, F(1, 3)),      # conjugate triplet; index equals fund
    ("ubarR", 3, 1, F(-2, 3)),
    ("lL",    1, 2, F(-1, 2)),
    ("ebarR", 1, 1, F(1, 1)),
    ("nbarR", 1, 1, F(0, 1)),
]


def _anomaly_sums(multiplets):
    su3 = sum(F(1, 2) * d2 * y for (_, d3, d2, y) in multiplets if d3 == 3)
    su2 = sum(F(1, 2) * d3 * y for (_, d3, d2, y) in multiplets if d2 == 2)
    y3 = sum(d3 * d2 * y ** 3 for (_, d3, d2, y) in multiplets)
    grav = sum(d3 * d2 * y for (_, d3, d2, y) in multiplets)
    doublets = sum(d3 for (_, d3, d2, y) in multiplets if d2 == 2)
    return {
        "su3_su3_u1": su3,
        "su2_su2_u1": su2,
        "u1_cubed": y3,
        "grav_grav_u1": grav,
        "witten_doublets": doublets,
    }


def run_generation() -> dict:
    total_states = sum(d3 * d2 for (_, d3, d2, _) in GENERATION)
    sums = _anomaly_sums(GENERATION)
    ok = (sums["su3_su3_u1"] == 0 and sums["su2_su2_u1"] == 0
          and sums["u1_cubed"] == 0 and sums["grav_grav_u1"] == 0
          and sums["witten_doublets"] % 2 == 0)
    deletions = {}
    for i, (name, *_rest) in enumerate(GENERATION):
        rest = GENERATION[:i] + GENERATION[i + 1:]
        s = _anomaly_sums(rest)
        broken = [k for k in ("su3_su3_u1", "su2_su2_u1", "u1_cubed",
                              "grav_grav_u1") if s[k] != 0]
        if s["witten_doublets"] % 2 == 1:
            broken.append("witten_parity")
        deletions[name] = broken
    return {
        "multiplets": [{"name": n, "su3": d3, "su2": d2,
                        "hypercharge": str(y), "states": d3 * d2}
                       for (n, d3, d2, y) in GENERATION],
        "total_weyl_states": total_states,
        "anomaly_sums": {k: str(v) for k, v in sums.items()},
        "all_conditions_hold": ok,
        "deletion_breaks": deletions,
        "deletions_that_break_nothing": [k for k, v in deletions.items()
                                         if not v],
    }


# ----------------------------------------------------------------------
# mechanism 2: the global-form atlas
# ----------------------------------------------------------------------
# Center classes live in Z3 x Z2 x Z6: color triality t, weak duality d,
# and hypercharge class y = 6Y mod 6. The Z6 generator acts on a class by
# the phase (t/3 + d/2 + y/6) mod 1; Gamma is generated by powers of the
# order-6 element z = (1, 1, 1) acting through that phase.

def _cls(d3, d2, y):
    t = {1: 0, 3: 1}[d3] if d3 in (1, 3) else None
    # conjugate triplets carry triality 2; encode via the sign of Y usage:
    return t, {1: 0, 2: 1}[d2], int(6 * y) % 6


MATTER_CLASSES = {
    "qL":    (1, 1, 1),
    "dbarR": (2, 0, 2),
    "ubarR": (2, 0, 2),
    "lL":    (0, 1, 3),
    "ebarR": (0, 0, 0),
    "nbarR": (0, 0, 0),
}

GAMMAS = {"1": 6, "Z2": 3, "Z3": 2, "Z6": 1}   # name -> generator power k
                                               # Gamma = <z^k>, |Gamma| = 6/k... see below


def _phase(cls, power):
    """Phase (in units of 1/6) with which z^power acts on a class."""
    t, d, y = cls
    # z = (omega, -1, e^{i pi /3}) acting on (t, d, y): phase = 2t/6? Use
    # sixths: t contributes 2t, d contributes 3d, y contributes y, mod 6.
    return (power * (2 * t + 3 * d + y)) % 6


def run_global_forms() -> dict:
    # the screening subgroup generated by matter classes in Z3 x Z2 x Z6
    def add(a, b):
        return ((a[0] + b[0]) % 3, (a[1] + b[1]) % 2, (a[2] + b[2]) % 6)

    screen = {(0, 0, 0)}
    frontier = list(MATTER_CLASSES.values())
    while frontier:
        nxt = []
        for s in list(screen):
            for m in frontier:
                x = add(s, m)
                if x not in screen:
                    screen.add(x)
                    nxt.append(x)
        frontier = nxt
    all_classes = [(t, d, y) for t in range(3) for d in range(2)
                   for y in range(6)]
    n_classes = len(all_classes)

    forms = {}
    gamma_orders = {"1": 1, "Z2": 2, "Z3": 3, "Z6": 6}
    for name, order in gamma_orders.items():
        k = 6 // order                      # Gamma = <z^k>
        # Wilson classes allowed in G/Gamma: trivial phase under z^k
        wilson = [c for c in all_classes if _phase(c, k) == 0] \
            if order > 1 else all_classes
        # matter admissibility
        matter_ok = all(_phase(MATTER_CLASSES[m], k) == 0
                        for m in MATTER_CLASSES) if order > 1 else True
        # electric one-form classes: allowed Wilson classes modulo screening
        wilson_set = set(wilson)
        # count cosets of the screening subgroup inside the allowed classes
        seen, cosets = set(), 0
        for c in wilson:
            if c in seen:
                continue
            cosets += 1
            for s in screen:
                seen.add(add(c, s))
        forms[name] = {
            "gamma_order": order,
            "n_wilson_classes": len(wilson),
            "electric_one_form_order": cosets,
            "magnetic_one_form_order": order,
            "product": cosets * order,
            "matter_admissible": matter_ok,
        }

    # Dirac pairing on the Z6 electric x Z6 magnetic torus: a pair
    # (e, m') is mutually local with (e', m) iff (e m' - e' m) = 0 mod 6.
    # For each Gamma the allowed set is E x M with E = <gamma_order'>?
    # Concretely: E_k = multiples of k in Z6 has order 6/k, M_k = subgroup
    # of order k; check pairing integral within each allowed lattice.
    pairing_ok = {}
    lattices = {}
    for name, order in gamma_orders.items():
        k = 6 // order
        E = [e for e in range(6) if e % (order if order < 6 else 6) == 0] \
            if order > 1 else list(range(6))
        E = sorted({(e * 1) % 6 for e in range(0, 6, max(1, order))})
        M = sorted({(m * k) % 6 for m in range(order)})
        ok = all((e * m) % 6 == 0 for e in E for m in M)
        pairing_ok[name] = ok
        lattices[name] = {"electric": E, "magnetic": M}
    distinct = len({(tuple(v["electric"]), tuple(v["magnetic"]))
                    for v in lattices.values()})
    return {
        "n_center_classes": n_classes,
        "screening_subgroup_order": len(screen),
        "matter_classes": {k: list(v) for k, v in MATTER_CLASSES.items()},
        "forms": forms,
        "lattices": lattices,
        "dirac_pairing_integral": pairing_ok,
        "n_distinct_lattices": distinct,
    }


# ----------------------------------------------------------------------
# mechanism 3: the SL(2,Z) orbit
# ----------------------------------------------------------------------

BOX = 40


def run_sl2z() -> dict:
    n_total = 0
    n_prim = 0
    orbit_iff_coprime = True
    decomposable = 0
    for p in range(-BOX, BOX + 1):
        for q in range(-BOX, BOX + 1):
            if (p, q) == (0, 0):
                continue
            n_total += 1
            g = math.gcd(p, q)
            if g == 1:
                n_prim += 1
                # constructive Bezout witness: p*s - q*r = 1
                r, s = _bezout(p, q)
                if p * s - q * r != 1:
                    orbit_iff_coprime = False
                # the no-go: a two-constituent decomposition with both
                # parts nonzero
                a, b = (1, 0) if (p, q) != (1, 0) else (2, 0)
                c, d = p - a, q - b
                if (a, b) != (0, 0) and (c, d) != (0, 0):
                    decomposable += 1
    density = n_prim / n_total
    return {
        "box": BOX,
        "n_vectors": n_total,
        "n_primitive": n_prim,
        "primitive_density": round(density, 6),
        "six_over_pi_squared": round(6 / math.pi ** 2, 6),
        "density_gap_pct": round(100 * abs(density - 6 / math.pi ** 2)
                                 / (6 / math.pi ** 2), 3),
        "orbit_iff_coprime_verified": orbit_iff_coprime,
        "primitive_all_decomposable": decomposable == n_prim,
    }


def _bezout(p, q):
    """Return (r, s) with p*s - q*r = 1 for coprime (p, q)."""
    # extended euclid on (p, q): find x, y with p*x + q*y = 1
    old_r, r = p, q
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r != 0:
        quot = old_r // r
        old_r, r = r, old_r - quot * r
        old_s, s = s, old_s - quot * s
        old_t, t = t, old_t - quot * t
    # p*old_s + q*old_t = old_r = +-gcd = +-1
    sign = old_r  # +1 or -1
    x, y = old_s * sign, old_t * sign
    # want p*s' - q*r' = 1: take s' = x, r' = -y
    return -y, x


# ----------------------------------------------------------------------
# mechanism 4: the fusion counterexamples
# ----------------------------------------------------------------------

def _su3_decompose(weights):
    """Decompose a weight multiset (dict weight -> multiplicity) into
    irreducibles of su(3) by iterative highest-weight peeling."""
    # weights are (a, b) in the Dynkin basis; dominance order by peeling
    from collections import Counter
    W = Counter(weights)
    content = Counter()
    while any(v > 0 for v in W.values()):
        # find the highest weight present: maximize (a+b, a) lexicographic
        hw = max((w for w, m in W.items() if m > 0),
                 key=lambda w: (w[0] + w[1], w[0]))
        mult = W[hw]
        content[hw] += mult
        for w, m in _irrep_weights_su3(hw).items():
            W[w] -= mult * m
    return dict(content)


def _irrep_weights_su3(hw):
    """Weight multiplicities of the su(3) irrep with highest weight
    (a, b), via Freudenthal on a small grid."""
    a, b = hw
    # generate candidate weights: hw - n1*alpha1 - n2*alpha2
    # in Dynkin basis: alpha1 = (2, -1), alpha2 = (-1, 2)
    from collections import Counter
    cand = {}
    for n1 in range(0, a + b + 3):
        for n2 in range(0, a + b + 3):
            w = (a - 2 * n1 + n2, b + n1 - 2 * n2)
            cand[(n1, n2)] = w
    # Freudenthal recursion by level
    mult = {(0, 0): 1}
    rho = (1, 1)

    def ip(u, v):
        # inner product in Dynkin basis via the su(3) quadratic form
        # (u, v) = u^T F v with F = (1/3) [[2,1],[1,2]]
        return F(2 * u[0] * v[0] + u[0] * v[1] + u[1] * v[0]
                 + 2 * u[1] * v[1], 3)

    levels = sorted(cand, key=lambda n: n[0] + n[1])
    hw_v = (a, b)
    for n in levels:
        if n == (0, 0):
            continue
        w = cand[n]
        num = F(0)
        for alpha, step in ((( 2, -1), (1, 0)), ((-1, 2), (0, 1)),
                            (( 1,  1), (1, 1))):
            k = 1
            while True:
                nn = (n[0] - k * step[0], n[1] - k * step[1])
                if nn[0] < 0 or nn[1] < 0 or nn not in cand:
                    break
                m_up = mult.get(nn, 0)
                if m_up:
                    wk = (w[0] + k * alpha[0], w[1] + k * alpha[1])
                    num += m_up * ip(wk, alpha)
                k += 1
        denom = (ip((hw_v[0] + rho[0], hw_v[1] + rho[1]),
                    (hw_v[0] + rho[0], hw_v[1] + rho[1]))
                 - ip((w[0] + rho[0], w[1] + rho[1]),
                      (w[0] + rho[0], w[1] + rho[1])))
        m = 2 * num / denom if denom != 0 else F(0)
        if m > 0:
            mult[n] = int(m)
    out = Counter()
    for n, m in mult.items():
        out[cand[n]] += m
    return dict(out)


def _tensor_su3(hw1, hw2):
    from collections import Counter
    w1 = _irrep_weights_su3(hw1)
    w2 = _irrep_weights_su3(hw2)
    prod = Counter()
    for a, ma in w1.items():
        for b, mb in w2.items():
            prod[(a[0] + b[0], a[1] + b[1])] += ma * mb
    return _su3_decompose(prod)


def run_fusion() -> dict:
    F3 = (1, 0)          # fundamental 3
    # 3 x 3
    t33 = _tensor_su3(F3, F3)
    # (3 x 3) x 3
    from collections import Counter
    t333 = Counter()
    for hw, m in t33.items():
        for hw2, m2 in _tensor_su3(hw, F3).items():
            t333[hw2] += m * m2
    dim = lambda hw: (hw[0] + 1) * (hw[1] + 1) * (hw[0] + hw[1] + 2) // 2
    name = {(0, 0): "1", (1, 0): "3", (0, 1): "3bar", (2, 0): "6",
            (1, 1): "8", (3, 0): "10", (0, 2): "6bar"}
    singlet_in_33 = t33.get((0, 0), 0)
    singlet_in_333 = t333.get((0, 0), 0)
    dim_check_333 = sum(dim(h) * m for h, m in t333.items())

    # SU(2) fusion ring: irreps labeled by dimension n; n x m = |n-m|+1..n+m-1
    def su2_tensor(n, m):
        return list(range(abs(n - m) + 1, n + m, 2))

    max_dim = 8
    prime = {}
    summand_of_smaller = {}
    for n in range(2, max_dim + 1):
        # tensor-prime: no factorization n = a (x) b as a single irrep
        is_prime = True
        for a in range(2, n):
            for b in range(2, n):
                if su2_tensor(a, b) == [n]:
                    is_prime = False
        prime[n] = is_prime
        # bound-state realization: n as a summand of 2 (x) (n-1)
        summand_of_smaller[n] = n in su2_tensor(2, n - 1)

    return {
        "su3_3x3": {name.get(h, str(h)): m for h, m in sorted(t33.items())},
        "su3_3x3x3": {name.get(h, str(h)): m for h, m in sorted(t333.items())},
        "singlet_in_3x3": singlet_in_33,
        "singlet_in_3x3x3": singlet_in_333,
        "dim_check_3x3x3": dim_check_333,
        "su2_max_dim": max_dim,
        "su2_all_irreps_tensor_prime": all(prime.values()),
        "su2_all_composite_as_summand": all(summand_of_smaller.values()),
    }


# ----------------------------------------------------------------------
# invariants and orchestration
# ----------------------------------------------------------------------

def _checks(gen, glob, sl2, fus) -> dict:
    c = {}
    c["sixteen_weyl_states"] = gen["total_weyl_states"] == 16
    c["all_five_conditions_hold"] = gen["all_conditions_hold"]
    c["five_deletions_break"] = sum(
        1 for v in gen["deletion_breaks"].values() if v) == 5
    c["only_nu_breaks_nothing"] = gen["deletions_that_break_nothing"] == ["nbarR"]
    c["screening_subgroup_is_z6"] = glob["screening_subgroup_order"] == 6
    c["matter_admissible_under_all_forms"] = all(
        v["matter_admissible"] for v in glob["forms"].values())
    c["electric_magnetic_orders_multiply_to_six"] = all(
        v["product"] == 6 for v in glob["forms"].values())
    c["dirac_pairing_integral"] = all(glob["dirac_pairing_integral"].values())
    c["four_distinct_lattices"] = glob["n_distinct_lattices"] == 4
    c["orbit_iff_coprime"] = sl2["orbit_iff_coprime_verified"]
    c["primitive_density_near_6_over_pi2"] = sl2["density_gap_pct"] < 2.0
    c["every_primitive_decomposes"] = sl2["primitive_all_decomposable"]
    c["singlet_absent_in_3x3"] = fus["singlet_in_3x3"] == 0
    c["singlet_once_in_3x3x3"] = fus["singlet_in_3x3x3"] == 1
    c["dimension_check_27"] = fus["dim_check_3x3x3"] == 27
    c["su2_tensor_primality_universal"] = fus["su2_all_irreps_tensor_prime"]
    c["su2_bound_states_are_summands"] = fus["su2_all_composite_as_summand"]
    return c


def run() -> dict:
    gen = run_generation()
    glob = run_global_forms()
    sl2 = run_sl2z()
    fus = run_fusion()
    checks = _checks(gen, glob, sl2, fus)
    failed = [k for k, v in checks.items() if not v]
    if failed:
        raise SystemExit(f"INVARIANT FAILURES: {failed}")
    return {
        "generation": gen,
        "global_forms": glob,
        "sl2z": sl2,
        "fusion": fus,
        "constants": {"BOX": BOX, "SEED": SEED},
        "checks": checks,
    }
